# Fonts
# font_family                     VictorMono Nerd Font
# bold_font                       auto
# italic_font                     VictorMono Nerd Font Italic
# bold_italic_font                auto
font_family      family='Monaspace Neon Var' variable_name=MonaspaceNeonVar wght=268.8524 wdth=106.3858 slnt=0 features='+calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +liga'
bold_font        family='Monaspace Neon Var' variable_name=MonaspaceNeonVar wght=321.3114754098361 wdth=105.7065 slnt=0 features='+calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09'
italic_font      family='Monaspace Radon Var' variable_name=MonaspaceRadonVar wght=308.1967 wdth=100 slnt=-9.625 features='+calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +liga'
bold_italic_font family='Monaspace Radon Var' variable_name=MonaspaceRadonVar style=MonaspaceRadonVar-SemiBoldItalic wght=308.1967 wdth=100 slnt=-9.625 features='+calt +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +liga'

# Adjust baseline and cell_height for Monaspace font.
modify_font baseline -2
modify_font cell_height 140%

# Adjust undercurl style.
undercurl_style thick-sparse

font_size                       14
enable_audio_bell               no
disable_ligatures               cursor

placement_strategy              center

# Include
include                         $HOME/.config/kitty/colors.conf
include                         $HOME/.config/kitty/tabs.conf
include                         $HOME/.config/kitty/mappings.conf

# Padding
window_padding_width            0

# Cursors
cursor_shape                    beam
cursor_beam_thickness           1

# Size
remember_window_size            yes
initial_window_width            640
initial_window_height           400

# Layouts
enabled_layouts                 horizontal,splits,grid,fat
window_resize_step_cells        1
window_resize_step_lines        1

# Border
window_border_width             0

shell_integration               disabled

input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no
