## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

# Sets user-defined palette
palette = "catppuccin_mocha"

# Setups
format = "$directory $git_branch $conda $character"
right_format = """$git_status$cmd_duration $rust"""
add_newline = false

# Other languages configurations:
c.disabled = true
cmake.disabled = true
python.disabled = true
haskell.disabled = true
ruby.disabled = true
lua.disabled = true
perl.disabled = true
package.disabled = true
nodejs.disabled = true
java.disabled = true
golang.disabled = true

[conda]
format = '[$symbol$environment](green) '
ignore_base = false

# Prompt symbols 
[character]
success_symbol = "[](green bold)"
error_symbol = "[](pink)"

[rust]
format = "[[  ](fg:lavender)$version](fg:lavender)"
# nice

[directory]
format = "[ ](fg:pink)[$path](fg:lavender bold)"
truncation_length = 3
truncate_to_repo = false

[git_branch]
format = "[[ ](bg:none fg:green bold)$branch](bg:base fg:lavender)"
style = "bg:none fg:base"

[git_status]
# $all status$ahead_behind
format = "[$all_status$ahead_behind](fg:yellow)"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "  "
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
# duration & style 
format = "[[λ](fg:flamingo bold)$duration](fg:text)"
disabled = false

# Not used currently, since it is too slow
[custom.jj]
command = '''starship-jj --ignore-working-copy starship prompt'''
when = "jj root --ignore-working-copy"
symbol = "jj"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
