#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# Script to control prefered apps to launch for all themes
# Author: z0mbi3
# url:    https://github.com/gh0stzk

WIDGET_DIR="$HOME/.config/bspwm/eww"

case "$1" in
    --menu)
        rofi -show drun -theme "$HOME"/.config/bspwm/scripts/Launcher.rasi 
        ;;
    --rice)
        RiceSelector
        ;;
    --terminal)
        kitty 
        ;;
    --floating)
        kitty --class FloaTerm -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c
        ;;
    --update)
        kitty --hold --class FloaTerm -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c -e Updates --update-system
        ;;
    --checkupdates)
        kitty --hold --class Updating -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c -e Updates --print-updates
        ;;
    --netmanager)
		NetManagerDM
		;;
    --ranger)
        kitty --class FloaTerm -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c -e ranger
        ;;
    --nvim)
        kitty -e nvim
        ;;
    --btop)
        kitty --hold --class FloaTerm -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c -e btop
        ;;
    --music)
        kitty --class FloaTerm -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c -e ncmpcpp
        ;;
    --fetch)
        kitty --hold --class FloaTerm -o remember_window_size=no -o initial_window_width=180c -o initial_window_height=40c -e ~/.local/bin/sysfetch
        ;;
        # Apps
    --filemanager)
        thunar
        ;;
    --browser)
        firefox
        ;;
    --editor)
        geany
        ;;
    --obsidian)
        obsidian
        ;;
    --telegram)
        telegram-desktop
        ;;
    --soundcontrol)
        pavucontrol
        ;;
        # Eww Widgets
    --powermenu)
        eww -c "$WIDGET_DIR" open --toggle powermenu
        ;;
    --usercard)
        eww -c "$WIDGET_DIR" open --toggle launchermenu
        ;;
    --player)
        eww -c "$WIDGET_DIR" open --toggle music
        ;;
    --calendar)
        eww -c "$WIDGET_DIR" open --toggle date
        ;;
    *)
        echo "Invalid Option"
        ;;
esac
