# Languages configuration
[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "hx-lsp" ]
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[[language]]
name = "python"
language-servers = ["basedpyright", "ruff", "pylyzer"]
auto-format = true

[language-server.basedpyright-ls-helix]
command = "basedpyright-ls-helix"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pylyzer]
command = "pylyzer"
args = ["--server"]

[language-server.hx-lsp]
command = "hx-lsp"

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "hx-lsp" ]
