# Languages configuration
[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "hx-lsp" ]
[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'


[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
auto-format = true

# This is buggy for some reason rn, so just use uv added basedpyright
[language-server.basedpyright-ls-helix]
command = "basedpyright-ls-helix"
config = {}
[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.hx-lsp]
command = "hx-lsp"

[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "hx-lsp" ]
